# Generated by Django 6.0.4 on 2026-06-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('dashboard', 'Dashboard'), ('mesas', 'Mesas'), ('ordenes', 'Órdenes'), ('caja', 'Caja'), ('productos', 'Productos'), ('insumos', 'Insumos'), ('reportes', 'Reportes'), ('usuarios', 'Usuarios')], max_length=50)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('cajero', 'Cajero'), ('mesero', 'Mesero')], max_length=50)),
                ('puede_acceder', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'ordering': ['modulo', 'rol'],
                'unique_together': {('modulo', 'rol')},
            },
        ),
    ]
