# Generated by Django 6.0.4 on 2026-05-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(unique=True)),
                ('capacidad', models.SmallIntegerField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='libre', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'mesa',
                'ordering': ['numero'],
            },
        ),
    ]
