# Generated by Django 6.0.4 on 2026-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orden',
            name='plataforma_delivery',
            field=models.CharField(blank=True, choices=[('rappi', 'Rappi'), ('pedidos_ya', 'PedidosYa'), ('didi', 'DiDi Food'), ('otro', 'Otro')], max_length=15),
        ),
        migrations.AddField(
            model_name='orden',
            name='plataforma_otra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipo_orden',
            field=models.CharField(choices=[('mesa', 'Mesa'), ('llevar', 'Para llevar'), ('delivery', 'Delivery')], default='mesa', max_length=10),
        ),
    ]
