# Generated by Django 6.0.4 on 2026-06-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_add_delivery_fields_and_tipo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='impreso',
            field=models.BooleanField(default=False),
        ),
    ]
