# Generated by Django 6.0.4 on 2026-06-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='monto_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
