# Generated by Django 6.0.6 on 2026-06-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_caja_monto_final_alter_caja_monto_inicial'),
        ('ordenes', '0003_detalleorden_impreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo para efectivo: monto físico entregado por el cliente.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_operacion',
            field=models.CharField(blank=True, default='', help_text='Número de operación para pagos con tarjeta.', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ordenes.orden'),
        ),
    ]
