# Generated by Django 6.0.6 on 2026-07-16 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_pago_monto_recibido_pago_numero_operacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha_apertura'], 'verbose_name': 'Sesion de caja', 'verbose_name_plural': 'Sesiones de caja'},
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('estado',), name='unica_caja_abierta'),
        ),
    ]
