# Generated by Django 6.0.6 on 2026-07-18 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_caja_options_caja_unica_caja_abierta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('devolucion', 'Devolución de dinero'), ('error_cobro', 'Error de cobro'), ('reclamo', 'Producto no conforme / reclamo'), ('otro', 'Otro')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito', to='caja.pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de crédito',
                'verbose_name_plural': 'Notas de crédito',
                'db_table': 'nota_credito',
                'ordering': ['-fecha'],
            },
        ),
    ]
